services:
   runner:
      build: .
      environment:
         REPO_URL: ${REPO_URL}
         RUNNER_NAME: ${RUNNER_NAME}
         RUNNER_TOKEN: ${RUNNER_TOKEN}
         RUNNER_WORKDIR: ${RUNNER_WORKDIR}
         LABELS: ${LABELS}
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock
         - ./runner:/tmp/github-runner
